version: "1"
rules:
  - base: stable
    upstream: northportio:stable
    mergeMethod: merge
    assignees:
      - northportio
    reviewers:
      - northportio
  - base: experimental
    upstream: northportio:experimental
    mergeMethod: none
    assignees:
      - northportio
    reviewers:
      - northportio
  - base: escape23
    upstream: northportio:escape23
    mergeMethod: merge
    assignees:
      - northportio
    reviewers:
      - northportio
  - base: staging
    upstream: northportio:staging
    mergeMethod: merge
    assignees:
      - northportio
    reviewers:
      - northportio
  - base: staging-DONOTUSE
    upstream: northportio:staging-DONOTUSE
    mergeMethod: merge
    assignees:
      - northportio
    reviewers:
      - northportio
  - base: staging-rainny
    upstream: northportio:staging-rainny
    mergeMethod: merge
    assignees:
      - northportio
    reviewers:
      - northportio
